services:
  # model
  object_manager:
    class: AppBundle\Model\ObjectManager

  import_csv_user:
    class: AppBundle\Model\ImportCsvUser
    arguments: ["@=service('doctrine.orm.entity_manager')", "@service('validator')", "@builder_import_user_factory", "@manager_import_user", "@builder_import_result_factory"]

  # entity
  entity_import_user:
    class: AppBundle\Entity\ImportUser

  # builder
  builder_import_user_factory:
    class: AppBundle\Model\Builder\ImportUserFactory
    arguments: ["@entity_import_user"]

  builder_import_result_factory:
   class: AppBundle\Model\Builder\ImportResultFactory
   arguments: ["@object_manager"]

  # manager
  manager_import_user:
    class: AppBundle\Model\ImportUserManager
    arguments: ["@=service('doctrine.orm.entity_manager')"]

  # csv/builder
  csv_builder_row_factory:
     class: AppBundle\Model\Csv\Builder\RowFactory
     arguments: ["@object_manager"]

  csv_builder_reader_factory:
    class: AppBundle\Model\Csv\Builder\ReaderFactory
    arguments: ["@object_manager", "@csv_builder_row_factory"]
