AppBundle\Entity\ImportUser:
  properties:
    firstName:
      - NotBlank: ~
      - Length:
          min: 1
          max: 255
    birthDate:
      - Date: ~
    gender:
      - AppBundle\Validator\Constraints\Gender: ~
